version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: persons
      POSTGRES_USER: persons
      POSTGRES_PASSWORD: pass
    volumes:
      - ../pkg/storage/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  httpserver:
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        - SVC=httpserver
    ports: 
      - 8081:8081
    environment: 
      - HTTP_LISTEN_ADDRESS
      - HTTP_GRPC_ADDRESS

  grpcserver:
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        - SVC=grpcserver
    ports: 
      - 50051:50051
    environment:
      - GRPC_LISTEN_ADDRESS