version: '3.1'
services:
  httpserver:
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        - SVC=httpserver
    ports: 
      - 8081:8081
    environment: 
      - HTTP_LISTEN_ADDRESS
      - HTTP_GRPC_ADDRESS
      - MONGO_ADDRESS
      - DB_TYPE
      - REDIS_ADDRESS
      - PG_ADDRESS
      - JWT_SECRET
    volumes:
      - ./templates:/templates

  grpcserver:
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        - SVC=grpcserver
    ports: 
      - 50051:50051
    environment:
      - GRPC_LISTEN_ADDRESS
      - MONGO_ADDRESS
      - DB_TYPE
      - REDIS_ADDRESS
      - PG_ADDRESS
  
  redis:
    image: redis
    profiles:
      - redis
  
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes: 
      - ../pkg/storage/mongostorage/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27017-27019:27017-27019'
    profiles: 
      - mongo
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: persons
      POSTGRES_USER: persons
      POSTGRES_PASSWORD: pass
    volumes:
      - ../pkg/storage/pgstorage/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    profiles:
      - postgres

      