// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Person struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type AddUpdatePerson struct {
	Name string `json:"name"`
}
